[package]
name = "rumt"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
tokio = { version = "1.48.0", features = ["full"] }
futures = "0.3" 
async-trait = "0.1"

[lib]
name = "rumt"
path = "src/lib.rs"
